"""empty message

Revision ID: 21aa5cae2227
Revises: b8698dd7f76d
Create Date: 2020-04-30 06:56:04.190683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aa5cae2227'
down_revision = 'b8698dd7f76d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
