"""empty message

Revision ID: 82211243eb8e
Revises: 6968dea062c5
Create Date: 2020-04-30 03:33:10.731083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82211243eb8e'
down_revision = '6968dea062c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.drop_constraint('Show_artist_shows_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venue_shows_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Show', 'artist_shows')
    op.drop_column('Show', 'venue_shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_shows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('artist_shows', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_venue_shows_fkey', 'Show', 'Venue', ['venue_shows'], ['id'])
    op.create_foreign_key('Show_artist_shows_fkey', 'Show', 'Artist', ['artist_shows'], ['id'])
    op.drop_column('Show', 'venue_id')
    op.drop_column('Show', 'artist_id')
    # ### end Alembic commands ###
